import { readFileSync } from 'fs';
import { join } from 'path';
import he from 'he';

// Load the baseline
const baselinePath = join(process.cwd(), 'src/data/seo_baseline.json');
const baseline = JSON.parse(readFileSync(baselinePath, 'utf8'));

// We will fetch a few random paths from the local build server
// and verify their title/meta tags match exactly.

async function verifySEO() {
    console.log("Starting Pre-Flight SEO Verification...\n");

    // Pick 3 random URLs from the baseline to test
    const targetUrls = [
        "https://valleywindowcare.com/roof-cleaning-company-in-green-bay-wisconsin/",
        "https://valleywindowcare.com/pressure-washing-company-in-green-bay-wisconsin/",
        "https://valleywindowcare.com/window-cleaning-company-in-green-bay-wisconsin/"
    ];

    let allPassed = true;

    for (const url of targetUrls) {
        const urlObj = new URL(url);
        // Our local build runs on localhost:3001 typically, or the static files in .next/server/app
        // For a robust test without needing the server running, we can read the generated HTML directly from the .next build folder

        let slug = urlObj.pathname;
        if (slug.endsWith('/')) slug = slug.slice(0, -1);

        const htmlFilePath = join(process.cwd(), ".next/server/app", `${slug}.html`);

        try {
            const htmlContent = readFileSync(htmlFilePath, 'utf8');

            // Raw expected strings from our original legacy site map
            const rawExpectedTitle = baseline[url]?.meta_title || baseline[slug]?.meta_title;
            const rawExpectedDesc = baseline[url]?.meta_description || baseline[slug]?.meta_description;

            // Decode expected strings because the JSON contains HTML entities (like &#039;)
            const expectedTitle = rawExpectedTitle ? he.decode(rawExpectedTitle) : null;
            const expectedDesc = rawExpectedDesc ? he.decode(rawExpectedDesc) : null;

            // Simple regex to extract <title> and <meta name="description"> generated by Next.js
            const titleMatch = htmlContent.match(/<title[^>]*>([\s\S]*?)<\/title>/i);
            const descMatch = htmlContent.match(/<meta[^>]*name="description"[^>]*content="([\s\S]*?)"[^>]*>/i) || htmlContent.match(/<meta[^>]*content="([\s\S]*?)"[^>]*name="description"[^>]*>/i);

            // Decode actual strings because Next.js encodes output (like '&' to '&amp;')
            const actualTitle = titleMatch ? he.decode(titleMatch[1].trim()) : null;
            const actualDesc = descMatch ? he.decode(descMatch[1].trim()) : null;

            console.log(`Checking Route: ${slug}`);
            console.log(`  Expected Title: "${expectedTitle}"`);
            console.log(`  Actual Title:   "${actualTitle}"`);
            if (expectedTitle !== actualTitle) {
                console.error("  ❌ TITLE MISMATCH");
                allPassed = false;
            } else {
                console.log("  ✅ Title Match");
            }

            console.log(`  Expected Desc:  "${expectedDesc}"`);
            console.log(`  Actual Desc:    "${actualDesc}"`);
            if (expectedDesc !== actualDesc) {
                console.error("  ❌ DESCRIPTION MISMATCH");
                allPassed = false;
            } else {
                console.log("  ✅ Description Match");
            }
            console.log("--------------------------------------------------\n");

        } catch (e) {
            console.error(`❌ Could not verify ${slug}: File not generated or not found.`);
            allPassed = false;
        }
    }

    if (allPassed) {
        console.log("✅✅✅ PRE-FLIGHT SEO VERIFICATION PASSED. ALL TAGS MATCH LEGACY BASELINE PERFECTLY.");
    } else {
        console.error("❌❌❌ PRE-FLIGHT SEO VERIFICATION FAILED. TAG MISMATCH DETECTED.");
        process.exit(1);
    }
}

verifySEO();
